name: CI for Python app - HobbyHive

on:
  push:
    branches: [ranjan]


jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary azure-identity

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Migrations
      env:
        AZURE_POSTGRESQL_HOST: ${{ secrets.AZURE_POSTGRESQL_HOST }}
        AZURE_POSTGRESQL_USERNAME: ${{ secrets.AZURE_POSTGRESQL_USERNAME }}
        DB_NAME: ${{ secrets.AZURE_POSTGRESQL_DBNAME }}
      run: |
        export DATABASE_URL="postgresql://${AZURE_POSTGRESQL_USERNAME}@${AZURE_POSTGRESQL_HOST}/${DB_NAME}"
        python manage.py migrate
    
    - name: Run Tests
      env:
        AZURE_POSTGRESQL_HOST: ${{ secrets.AZURE_POSTGRESQL_HOST }}
        AZURE_POSTGRESQL_USERNAME: ${{ secrets.AZURE_POSTGRESQL_USERNAME }}
        DB_NAME: ${{ secrets.AZURE_POSTGRESQL_DBNAME }}
      run: |
        export DATABASE_URL="postgresql://${AZURE_POSTGRESQL_USERNAME}@${AZURE_POSTGRESQL_HOST}/${DB_NAME}"
        python manage.py test
    
    - name: Run Coverage
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report