name: Django Project Diagnostics

on:
  push:
    branches: [ ranjan ]

jobs:
  diagnose:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Adjust to your project's Python version
    
    - name: System Information
      run: |
        echo "--- System Details ---"
        uname -a
        python --version
        pwd
        ls -la
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary dj-database-url
    
    - name: Print Environment
      run: |
        echo "--- Python Path ---"
        python -m site
        
        echo "--- Installed Packages ---"
        pip freeze
    
    - name: Check Django Configuration
      run: |
        echo "--- Django Check ---"
        python manage.py check
        python manage.py makemigrations --check
    
    - name: Verbose Troubleshooting
      env:
        DJANGO_SETTINGS_MODULE: hobby_hive.settings  # REPLACE with your actual settings module
      run: |
        echo "--- Verbose Django Check ---"
        python -m django --version
        python manage.py diffsettings
        python manage.py inspectdb