name: Django Tests

on:
  push:
    branches: [ ranjan ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary python-dotenv dj-database-url
    
    - name: Create .env File
      env:
        AZURE_POSTGRESQL_HOST: ${{ secrets.AZURE_POSTGRESQL_HOST }}
        AZURE_POSTGRESQL_USERNAME: ${{ secrets.AZURE_POSTGRESQL_USERNAME }}
        AZURE_POSTGRESQL_PASSWORD: ${{ secrets.AZURE_POSTGRESQL_PASSWORD }}
        AZURE_POSTGRESQL_DBNAME: ${{ secrets.AZURE_POSTGRESQL_DBNAME }}
      run: |
        echo "DATABASE_URL=postgresql://${AZURE_POSTGRESQL_USERNAME}:${AZURE_POSTGRESQL_PASSWORD}@${AZURE_POSTGRESQL_HOST}/${AZURE_POSTGRESQL_DBNAME}" > .env.deployment
        cat .env.deployment
    
    - name: Verify Database Connection
      env:
        AZURE_POSTGRESQL_HOST: ${{ secrets.AZURE_POSTGRESQL_HOST }}
        AZURE_POSTGRESQL_USERNAME: ${{ secrets.AZURE_POSTGRESQL_USERNAME }}
        AZURE_POSTGRESQL_PASSWORD: ${{ secrets.AZURE_POSTGRESQL_PASSWORD }}
        AZURE_POSTGRESQL_DBNAME: ${{ secrets.AZURE_POSTGRESQL_DBNAME }}
      run: |
        python -c "
        import psycopg2
        try:
            conn = psycopg2.connect(
            host='$AZURE_POSTGRESQL_HOST',
            database='$AZURE_POSTGRESQL_DBNAME',
            user='$AZURE_POSTGRESQL_USERNAME',
            password='$AZURE_POSTGRESQL_PASSWORD',
            sslmode='require'
            )
            print('Successfully connected to the database')
            conn.close()
        except Exception as e:
            print(f'Connection failed: {e}')
            exit(1)
        "
    
    - name: Run Migrations
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings.deployment
      run: |
        python manage.py migrate
    
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings.deployment
      run: |
        python manage.py test