name: Django Tests with SSL

on:
  push:
    branches: [ ranjan]


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary
    
    - name: Download Azure PostgreSQL SSL Certificate
      run: |
        # Replace URL with the actual URL of your Azure PostgreSQL root certificate
        wget https://www.digicert.com/CACerts/BaltimoreCyberTrustRoot.crt -O azure_postgres_cert.pem
    
    - name: Run Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SSL_CERT_PATH: ${{ github.workspace }}/azure_postgres_cert.pem
      run: |
        export DATABASE_URL="${DATABASE_URL}?sslmode=verify-full&sslrootcert=$SSL_CERT_PATH"
        python manage.py migrate
    
    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SSL_CERT_PATH: ${{ github.workspace }}/azure_postgres_cert.pem
      run: |
        export DATABASE_URL="${DATABASE_URL}?sslmode=verify-full&sslrootcert=$SSL_CERT_PATH"
        python manage.py test