name: CI

on:
  push:
    branches:
      - ranjan

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ranjan
          POSTGRES_PASSWORD: Bigenergy613#
          POSTGRES_DB: postgres
        ports:
          - "5432:5432"
        options: > 
          --health-cmd="pg_isready -U postgres -d test_db" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # Adjust as per your project requirements

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Run black for code formatting checks
      - name: Run black
        run: |
          python -m black --check .

      # Run pytest for testing
      - name: Run tests
        env:
          DATABASE_URL: "postgres://ranjan:Bigenergy613#@hobbyhivedev.postgres.database.azure.com:5432/postgres"
        run: |
          python -m pytest --maxfail=5 --disable-warnings --tb=short
